<a href="https://colab.research.google.com/github/monp97/dataset/blob/master/gender_prediction_final_accuracy_45.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/monp97/dataset.git

Cloning into 'dataset'...
remote: Enumerating objects: 7685, done.
remote: Counting objects: 100% (7685/7685), done.
remote: Compressing objects: 100% (7425/7425), done.
remote: Total 70624 (delta 263), reused 7678 (delta 260), pack-reused 62939
Receiving objects: 100% (70624/70624), 454.04 MiB | 31.55 MiB/s, done.
Resolving deltas: 100% (3251/3251), done.
Checking out files: 100% (128228/128228), done.


In [0]:
import os

directory = "final_dataset"
  
# Parent Directory path 
parent_dir = "/content/"
  
# Path 
path = os.path.join(parent_dir, directory) 
  
# Create the directory 
# 'GeeksForGeeks' in 
# '/home / User / Documents' 
os.mkdir(path) 
print("Directory '% s' created" % directory) 

Directory 'final_dataset' created


In [0]:
directory1 = "training"
directory2 = "test"

# Parent Directory path 
parent_dir = "/content/final_dataset"
  
# Path 
path1 = os.path.join(parent_dir, directory1) 
path2 = os.path.join(parent_dir, directory2) 
  
# Create the directory 
# 'GeeksForGeeks' in 
# '/home / User / Documents' 
os.mkdir(path1) 
os.mkdir(path2) 

In [0]:
directories = ["female_left","male_left","female_right","male_right"]
  
# Parent Directory path 
parent_dir = "/content/final_dataset/training"

list_final_dir=[]

k=1

for dir in directories:
  for i in range(5):
    list_final_dir.append(dir+'_'+str(i+1)+'_0'+str(k))
    k+=1
  
# Path 
# path1 = os.path.join(parent_dir, directory1) 
# path2 = os.path.join(parent_dir, directory2) 

for i in range(len(list_final_dir)):
  path = os.path.join(parent_dir, list_final_dir[i]) 
  os.mkdir(path) 
   
# # Create the directory 
# # 'GeeksForGeeks' in 
# # '/home / User / Documents' 
# os.mkdir(path1) 
# os.mkdir(path2) 

In [0]:
directories = ["female_left","male_left","female_right","male_right"]

  
# Parent Directory path 
parent_dir = "/content/final_dataset/test"

list_final_dir=[]

k=1

for dir in directories:
  for i in range(5):
    list_final_dir.append(dir+'_'+str(i+1)+'_0'+str(k))
    k+=1
  
# Path 
# path1 = os.path.join(parent_dir, directory1) 
# path2 = os.path.join(parent_dir, directory2) 

for i in range(len(list_final_dir)):
  path = os.path.join(parent_dir, list_final_dir[i]) 
  os.mkdir(path) 

In [0]:
import cv2
import os
import shutil

dst = 'path/to/dest_dir'

images = []
i=0
f=0
m=0

dic={
    'female_left_1':"01",
    'female_left_2':"02",
    'female_left_3':"03",
    'female_left_4':"04",
    'female_left_5':"05",
    'female_right_1':"011",
    'female_right_2':"012",
    'female_right_3':"013",
    'female_right_4':"014",
    'female_right_5':"015",
    'male_left_1':"06",
    'male_left_2':"07",
    'male_left_3':"08",
    'male_left_4':"09",
    'male_left_5':"010",
    'male_right_1':"016",
    'male_right_2':"017",
    'male_right_3':"018",
    'male_right_4':"019",
    'male_right_5':"020",
}


for filename in os.listdir('/content/dataset/Real'):
        subject_id, etc = filename.split('__')
        gender, lr, finger, _ = etc.split('_')
        src='/content/dataset/Real/'+filename
        i=i+1

        refer = {
          "index": "1",
          "middle": "2",
          "ring":"3",
          "little":"4",
          "thumb":"5"
        }

        dir_name=''

        if gender=='M':
          dir_name=dir_name+'male_'
        else:
          dir_name=dir_name+'female_'

        if lr=='Left':
          dir_name=dir_name+'left_'
        else:
          dir_name=dir_name+'right_'

        dir_name=dir_name+refer[finger]

        name=dir_name

        dir_name=name+'_'+str(dic[name])

        shutil.copy(src,'/content/final_dataset/training/'+dir_name)

In [0]:
import shutil
import os
import numpy as np
import argparse

def get_files_from_folder(path):

    files = os.listdir(path)
    return np.asarray(files)

def main(path_to_data, path_to_test_data, train_ratio):
    # get dirs
    _, dirs, _ = next(os.walk(path_to_data))

    # calculates how many train data per class
    data_counter_per_class = np.zeros((len(dirs)))
    for i in range(len(dirs)):
        path = os.path.join(path_to_data, dirs[i])
        files = get_files_from_folder(path)
        data_counter_per_class[i] = len(files)
    test_counter = np.round(data_counter_per_class * (1 - train_ratio))

    # transfers files
    for i in range(len(dirs)):
        path_to_original = os.path.join(path_to_data, dirs[i])
        path_to_save = os.path.join(path_to_test_data, dirs[i])

        #creates dir
        if not os.path.exists(path_to_save):
            os.makedirs(path_to_save)
        files = get_files_from_folder(path_to_original)
        # moves data
        for j in range(int(test_counter[i])):
            dst = os.path.join(path_to_save, files[j])
            src = os.path.join(path_to_original, files[j])
            shutil.move(src, dst)

    
# def parse_args():
#   parser = argparse.ArgumentParser(description="Dataset divider")
#   parser.add_argument("--data_path", required=True,
#     help="Path to data")
#   parser.add_argument("--test_data_path_to_save", required=True,
#     help="Path to test data where to save")
#   parser.add_argument("--train_ratio", required=True,
#     help="Train ratio - 0.7 means splitting data in 70 % train and 30 % test")
#   return parser.parse_args()

if __name__ == "__main__":
  # args = parse_args()
  # args.data_path='/content/final_dataset/training'
  # args.test_data_path_to_save='/content/final_dataset/test'
  # args.train_ratio=0.8
  main('/content/final_dataset/training','/content/final_dataset/test', float(0.8))


In [0]:
source1 = "/content/final_dataset/training"
dest11 = "/content/final_dataset/test"

files1 = os.listdir(source1)
files2 = os.listdir(dest11)


for file in files1:
  files_file= os.listdir("/content/final_dataset/training/"+file)
  print("training data "+str(file)+' '+str(len(files_file)))


for file in files2:
  files_file= os.listdir("/content/final_dataset/test/"+file)
  print("test data "+str(file)+' '+str(len(files_file)))



training data female_left_3_03 98
training data male_left_1_06 382
training data female_right_2_012 98
training data male_left_3_08 382
training data male_right_1_016 382
training data female_left_4_04 98
training data female_right_1_011 98
training data male_left_4_09 382
training data female_left_5_05 98
training data male_right_4_019 382
training data female_right_3_013 98
training data female_left_2_02 98
training data female_left_1_01 98
training data male_left_5_010 382
training data male_right_5_020 382
training data male_right_3_018 382
training data female_right_4_014 98
training data male_left_2_07 382
training data male_right_2_017 382
training data female_right_5_015 98
test data female_left_3_03 25
test data male_left_1_06 95
test data female_right_2_012 25
test data male_left_3_08 95
test data male_right_1_016 95
test data female_left_4_04 25
test data female_right_1_011 25
test data male_left_4_09 95
test data female_left_5_05 25
test data male_right_4_019 95
test data f

In [0]:
import numpy as np
def processImage(img):
  gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
  res = cv2.resize(gray, dsize=(64, 64), interpolation=cv2.INTER_CUBIC)
  # print(res.shape)
  return res

In [0]:
from google.colab.patches import cv2_imshow
source1 = "/content/final_dataset/training"
files1 = os.listdir(source1)
img_list=[]
i=0
for file in files2:
  path="/content/final_dataset/training/"+file
  files_file= os.listdir(path)
  # print("test data "+str(file)+' '+str(len(files_file)))
  for file1 in files_file:
    image = cv2.imread(path+'/'+file1)
    preprocessed_img=processImage(image)
    tuple_img=np.append(preprocessed_img.flatten(),np.array([file]))
    img_list.append(tuple_img)


print(len(img_list))

import pandas as pd
df = pd.DataFrame(img_list)
print(df)
df.to_csv('img_bkup.csv', index=False)


4800
     0    1    2    3    4    5     ... 4091 4092 4093 4094 4095                4096
0     157  138  137  137  137  137  ...    0    0    0    0    0    female_left_3_03
1     157  138  137  137  137  137  ...    0    0    0    0    0    female_left_3_03
2     157  138  137  137  137  137  ...    0    0    0    0    0    female_left_3_03
3     157  138  137  137  137  137  ...    0    0    0    0    0    female_left_3_03
4     157  138  137  137  137  137  ...    0    0    0    0    0    female_left_3_03
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...                 ...
4795  157  138  137  137  137  137  ...    0    0    0    0    0  female_right_5_015
4796  157  138  137  137  137  137  ...    0    0    0    0    0  female_right_5_015
4797  157  138  137  137  137  137  ...    0    0    0    0    0  female_right_5_015
4798  157  138  137  137  137  137  ...    0    0    0    0    0  female_right_5_015
4799  157  138  137  137  137  137  ...    0    0    0    0 

In [0]:
import os

directory = "final_dataset_smote"
# Parent Directory path 
parent_dir = "/content/" 
# Path 
path = os.path.join(parent_dir, directory) 
# Create the directory 
# 'GeeksForGeeks' in 
# '/home / User / Documents' 
os.mkdir(path) 
print("Directory '% s' created" % directory) 

Directory 'final_dataset_smote' created


In [21]:
directory1 = "training"
directory2 = "test"

# Parent Directory path 
parent_dir = "/content/final_dataset_smote"
  
# Path 
path1 = os.path.join(parent_dir, directory1) 
path2 = os.path.join(parent_dir, directory2) 
  
# Create the directory 
# 'GeeksForGeeks' in 
# '/home / User / Documents' 
os.mkdir(path1) 
os.mkdir(path2) 

FileNotFoundError: ignored

In [0]:
directories = ["female_left","male_left","female_right","male_right"]
  
# Parent Directory path 
parent_dir = "/content/final_dataset_smote/training"

list_final_dir=[]

k=1

for dir in directories:
  for i in range(5):
    list_final_dir.append(dir+'_'+str(i+1)+'_0'+str(k))
    k+=1
  
# Path 
# path1 = os.path.join(parent_dir, directory1) 
# path2 = os.path.join(parent_dir, directory2) 

for i in range(len(list_final_dir)):
  path = os.path.join(parent_dir, list_final_dir[i]) 
  os.mkdir(path) 

In [0]:
import os
directories = ["female_left","male_left","female_right","male_right"]
  
# Parent Directory path 
parent_dir = "/content/final_dataset_smote/test"

list_final_dir=[]

k=1

for dir in directories:
  for i in range(5):
    list_final_dir.append(dir+'_'+str(i+1)+'_0'+str(k))
    k+=1
  
# Path 
# path1 = os.path.join(parent_dir, directory1) 
# path2 = os.path.join(parent_dir, directory2) 

for i in range(len(list_final_dir)):
  path = os.path.join(parent_dir, list_final_dir[i]) 
  os.mkdir(path) 

In [0]:
import pandas as pd

from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state = 20)
df=pd.read_csv('/content/img_bkup.csv')
X_train=df.iloc[:, :-1]
y_train=df.iloc[:,-1]
# print(X_train)
# print(y_train)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel()) 

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [0]:
X_train_res.shape

(7640, 4096)

In [0]:
y_train_res.shape

(7640,)

In [0]:
smote_img_arr_res=np.hstack((X_train_res,y_train_res.reshape(7640,1)))

In [0]:
print(smote_img_arr_res)

[[157 138 137 ... 0 0 'female_left_3_03']
 [157 138 137 ... 0 0 'female_left_3_03']
 [157 138 137 ... 0 0 'female_left_3_03']
 ...
 [157 138 137 ... 0 0 'female_right_5_015']
 [157 138 137 ... 0 0 'female_right_5_015']
 [157 138 137 ... 0 0 'female_right_5_015']]


In [0]:
import pandas as pd
df = pd.DataFrame(smote_img_arr_res)
df.to_csv('smote_img_bkup.csv', index=False)

In [0]:
df=pd.read_csv('/content/smote_img_bkup.csv')
img=df.iloc[:, :-1]
labels=df.iloc[:,-1]

np_arr_img=img.values
labels_arr_img=labels.values

dic={
    'female_left_1_01':0,
    'female_left_2_02':0,
    'female_left_3_03':0,
    'female_left_4_04':0,
    'female_left_5_05':0,
    'female_right_1_011':0,
    'female_right_2_012':0,
    'female_right_3_013':0,
    'female_right_4_014':0,
    'female_right_5_015':0,
    'male_left_1_06':0,
    'male_left_2_07':0,
    'male_left_3_08':0,
    'male_left_4_09':0,
    'male_left_5_010':0,
    'male_right_1_016':0,
    'male_right_2_017':0,
    'male_right_3_018':0,
    'male_right_4_019':0,
    'male_right_5_020':0,
}


for i in range(7640):
  img=np_arr_img[i].reshape(64,64)
  label=labels_arr_img[i]
  count=dic[label]
  dic[label]=count+1
  dest='/content/final_dataset_smote/training/'+label+'/'
  cv2.imwrite(os.path.join(dest, label+'_'+str(dic[label])+'.BMP'), img)



  


In [0]:
source1 = "/content/final_dataset_smote/training"
dest11 = "/content/final_dataset_smote/test"

files1 = os.listdir(source1)
files2 = os.listdir(dest11)


for file in files1:
  files_file= os.listdir("/content/final_dataset_smote/training/"+file)
  print("training data "+str(file)+' '+str(len(files_file)))


for file in files2:
  files_file= os.listdir("/content/final_dataset_smote/test/"+file)
  print("test data "+str(file)+' '+str(len(files_file)))

training data female_left_3_03 383
training data male_left_1_06 382
training data female_right_2_012 382
training data male_left_3_08 382
training data male_right_1_016 382
training data female_left_4_04 382
training data female_right_1_011 382
training data male_left_4_09 382
training data female_left_5_05 382
training data male_right_4_019 382
training data female_right_3_013 382
training data female_left_2_02 382
training data female_left_1_01 382
training data male_left_5_010 382
training data male_right_5_020 382
training data male_right_3_018 382
training data female_right_4_014 382
training data male_left_2_07 382
training data male_right_2_017 382
training data .ipynb_checkpoints 0
training data female_right_5_015 382
test data female_left_3_03 25
test data male_left_1_06 95
test data female_right_2_012 25
test data male_left_3_08 95
test data male_right_1_016 95
test data female_left_4_04 25
test data female_right_1_011 25
test data male_left_4_09 95
test data female_left_5_05

In [30]:
from distutils.dir_util import copy_tree
from os import listdir,makedirs
from os.path import isfile,join
import cv2

# copy subdirectory example
fromDirectory = "/a/b/c"
toDirectory = "/x/y/z"

source1 = "/content/dataset/smote_dataset/final_dataset_smote/test"
files1 = os.listdir(source1)

print(files)

for folder in files1:
  path=source1+'/'+folder
  dstpath='/content/dataset/final_dataset_smote/test/'+folder
  files = os.listdir(path)
  for image in files:
    img = cv2.imread(os.path.join(path,image))
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    dstPath = join(dstpath,image)
    cv2.imwrite(dstPath,gray)


['24__F_Right_ring_finger.BMP', '42__F_Right_ring_finger.BMP', '154__F_Right_ring_finger.BMP', '452__F_Right_ring_finger.BMP', '334__F_Right_ring_finger.BMP', '191__F_Right_ring_finger.BMP', '572__F_Right_ring_finger.BMP', '556__F_Right_ring_finger.BMP', '494__F_Right_ring_finger.BMP', '379__F_Right_ring_finger.BMP', '109__F_Right_ring_finger.BMP', '536__F_Right_ring_finger.BMP', '551__F_Right_ring_finger.BMP', '449__F_Right_ring_finger.BMP', '369__F_Right_ring_finger.BMP', '30__F_Right_ring_finger.BMP', '48__F_Right_ring_finger.BMP', '201__F_Right_ring_finger.BMP', '66__F_Right_ring_finger.BMP', '289__F_Right_ring_finger.BMP', '275__F_Right_ring_finger.BMP', '47__F_Right_ring_finger.BMP', '13__F_Right_ring_finger.BMP', '470__F_Right_ring_finger.BMP', '502__F_Right_ring_finger.BMP']


In [39]:
# source1 = "/content/dataset/final_dataset_smote/test/female_left_1_01"
# files1 = os.listdir(source1)
from google.colab.patches import cv2_imshow

img = cv2.imread('/content/dataset/final_dataset_smote/test/female_left_1_01/140__F_Left_index_finger.BMP',cv2.IMREAD_GRAYSCALE)
print(img.shape)
print(img)

(103, 96)
[[160 160 160 ...   0   0   0]
 [160 105 105 ...   0   0   0]
 [160 105 255 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [0]:
import shutil
shutil.rmtree('/content/dataset/final_dataset_smote/test')

In [0]:
!zip -r /content/smote_data_2.zip /content/final_dataset_smote

In [72]:
from keras.preprocessing.image import ImageDataGenerator
import numpy as np



train_datagen=ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
   
)

test_datagen=ImageDataGenerator(rescale=1./255)

training_set=train_datagen.flow_from_directory(
    '/content/dataset/final_dataset_smote/training',
    target_size=(64,64),
    batch_size=64,
    color_mode="grayscale",
    class_mode='categorical',
    shuffle=True
)

test_set=test_datagen.flow_from_directory(
    '/content/dataset/final_dataset_smote/test',
    target_size=(64,64),
    batch_size=64,
    color_mode="grayscale",
    class_mode='categorical',
    shuffle=False
)

Found 7640 images belonging to 20 classes.
Found 1200 images belonging to 20 classes.


In [0]:
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout
from keras import optimizers

In [4]:
classifier=Sequential()
classifier.add(Convolution2D(64,3,3,input_shape=(64,64,1),activation='relu'))
classifier.add(MaxPooling2D(pool_size=(3,3)))

classifier.add(Convolution2D(128,3,3,activation='relu'))
classifier.add(MaxPooling2D(pool_size=(3,3)))
classifier.add(Flatten())
print(classifier.summary())





Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 64)        640       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 20, 20, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 18, 18, 128)       73856     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 6, 6, 128)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 4608)              0         
Total params: 74,496
Trainable params: 74,496
Non-trainable params: 0
_________________________________________________________________
None


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), input_shape=(64, 64, 1..., activation="relu")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), activation="relu")`
  """


In [0]:
import tensorflow as tf
import keras

def my_newCNN(input_shape, num_classes):
    model = Sequential()
    model.add(keras.layers.Conv2D(16, kernel_size=(3, 3), padding='same',
                            name='image_array', input_shape=input_shape, activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Conv2D(16, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Dropout(.25))
    model.add(keras.layers.SeparableConv2D(32, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Conv2D(32, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Dropout(.25))
    model.add(keras.layers.Conv2D(64, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Conv2D(64, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Dropout(.25))
    model.add(keras.layers.Conv2D(128, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Conv2D(128, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Dropout(.25))
    model.add(keras.layers.Conv2D(256, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Conv2D(256, kernel_size=(3, 3), padding='same',
                            strides=(2, 2), activation='relu'))
    model.add(keras.layers.BatchNormalization())
    model.add(keras.layers.Dropout(.25))
    model.add(keras.layers.Dense(128,activation='relu'))
    model.add(keras.layers.Dense(num_classes))
    model.add(keras.layers.Flatten())
    model.add(keras.layers.Activation('softmax',name='predictions'))
    return model

In [0]:
classifier=my_newCNN((64,64,1),20)

In [0]:
classifier.add(Dense(output_dim=128, activation='relu'))
classifier.add(Dropout(0.2))
classifier.add(Dense(output_dim=20,activation='softmax'))

In [0]:
opt = optimizers.adam(lr=0.01)
classifier.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['accuracy'])

In [77]:
from IPython.display import display
from PIL import Image


classifier.fit_generator(training_set,
                    steps_per_epoch=3200,
                    epochs=30,
                    validation_data=test_set,
                    nb_val_samples=800)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras_pre..., steps_per_epoch=3200, epochs=30, validation_data=<keras_pre..., validation_steps=800)`
  if __name__ == '__main__':


Epoch 1/30
3200/3200 [==============================] - 228s 71ms/step - loss: 2.0682 - acc: 0.3185 - val_loss: 3.5453 - val_acc: 0.1613
Epoch 2/30
3200/3200 [==============================] - 225s 70ms/step - loss: 1.7215 - acc: 0.4327 - val_loss: 2.1996 - val_acc: 0.3492
Epoch 3/30
3200/3200 [==============================] - 220s 69ms/step - loss: 1.5137 - acc: 0.5064 - val_loss: 2.0420 - val_acc: 0.4154
Epoch 4/30
3200/3200 [==============================] - 211s 66ms/step - loss: 1.3711 - acc: 0.5528 - val_loss: 1.8952 - val_acc: 0.4536
Epoch 5/30
3200/3200 [==============================] - 210s 66ms/step - loss: 1.2751 - acc: 0.5827 - val_loss: 2.2064 - val_acc: 0.4030
Epoch 6/30
3200/3200 [==============================] - 209s 65ms/step - loss: 1.1990 - acc: 0.6061 - val_loss: 1.9151 - val_acc: 0.4516
Epoch 7/30
3200/3200 [==============================] - 205s 64ms/step - loss: 1.1422 - acc: 0.6245 - val_loss: 2.0047 - val_acc: 0.4236
Epoch 8/30
3200/3200 [===================

In [0]:
from sklearn import metrics
# test_set.reset()
# val_trues = test_set.classes
# predictions= classifier.predict_generator(test_set, 1200 // 32)
# val_preds = np.argmax(predictions, axis=-1)
# val_trues = test_set.classes[:1184]
# print(len(val_trues))
# print(len(val_preds))
# # cm = metrics.confusion_matrix(val_trues, val_preds)
# labels = str(test_set.class_indices.keys())

# print(labels)

# precisions, recall, f1_score, _ = metrics.precision_recall_fscore_support(val_trues,predicted_class_indices, labels=labels)

# print(precisions)
# print(f1_score)

In [87]:
from sklearn.metrics import classification_report, confusion_matrix
Y_pred = classifier.predict_generator(test_set,1200 // 64)
print(len(Y_pred))
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(test_set.classes[:1152], y_pred))
print('Classification Report')
print(str(test_set.class_indices.keys()))
target_names = ['female_left_1_01', 'female_left_2_02', 'female_left_3_03', 'female_left_4_04', 'female_left_5_05', 'female_right_1_011', 'female_right_2_012', 'female_right_3_013', 'female_right_4_014', 'female_right_5_015', 'male_left_1_06', 'male_left_2_07', 'male_left_3_08', 'male_left_4_09', 'male_left_5_010', 'male_right_1_016', 'male_right_2_017', 'male_right_3_018', 'male_right_4_019', 'male_right_5_020']
print(classification_report(test_set.classes[:1152], y_pred, target_names=target_names))
 
 

1152
Confusion Matrix
[[ 2  0  0  0  0  0  1  0  0  0 21  0  0  0  0  1  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  6 15  1  2  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0  5  4  7  2  0  1  0  0  2  0]
 [ 3  1  1  4  1  0  0  0  0  0  7  0  0  4  2  0  0  1  1  0]
 [ 0  0  0  0  1  0  0  0  0  0  5  0  0  0 18  1  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  3  0  0  0  0 17  4  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  2  0  0  1  0  4 12  1  3  0]
 [ 1  0  0  0  0  0  0  2  0  0  6  0  1  1  0  2  2  6  4  0]
 [ 0  1  0  0  0  1  0  0  0  0  0  0  0  1  0  1  2  1 18  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  1  3  0  0  0 20]
 [ 1  0  0  0  0  0  0  0  0  0 83  1  0  2  3  1  2  1  1  0]
 [ 0  0  0  0  2  0  0  0  0  0 44 35  3  0  4  0  2  5  0  0]
 [ 0  0  2  0  0  0  0  0  0  0 16 16 36  5 14  4  2  0  0  0]
 [ 1  0  0  0  2  0  0  0  0  0 29  7  6 37  3  6  0  1  3  0]
 [ 0  0  0  0  4  0  0  0  0  0 11  1  0  0 78  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0 1

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
